# Generated by Django 5.0.4 on 2024-05-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
