# Generated by Django 5.0.4 on 2024-05-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0002_reservation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
