# Generated by Django 5.0.4 on 2024-05-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0003_reservation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='activeReservation',
            field=models.BooleanField(default=True),
        ),
    ]
