# Generated by Django 5.0.4 on 2024-05-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0003_reservation_returned'),
        ('reservation_management', '0004_reservation_activereservation'),
    ]

    operations = [
    ]
