# Generated by Django 5.0.4 on 2024-05-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_management', '0005_merge_20240501_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bookingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
