# Generated by Django 5.0.4 on 2024-04-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentName', models.CharField(max_length=100)),
                ('equipmentCondition', models.CharField(max_length=100)),
                ('equipmentType', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('auditDate', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('siteLocation', models.CharField(max_length=100)),
                ('accessLevel', models.CharField(max_length=100)),
                ('serialNo', models.CharField(max_length=100)),
                ('CPU', models.CharField(max_length=100)),
                ('RAM', models.IntegerField()),
                ('GPU', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
    ]
