# Generated by Django 5.0.4 on 2024-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='CPU',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='GPU',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='RAM',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipmentCondition',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='siteLocation',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipmentStatus',
            field=models.CharField(choices=[('On_loan', 'On Loan'), ('Repairing', 'Repairing'), ('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='comments',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(choices=[('blue_cabinet', 'XRLab Blue Cabinet'), ('blue_cabinet_large', 'XRLab Blue Cabinet Large'), ('medium_wooden_cabinet', 'XRLab Medium Wooden Cabinet'), ('other', 'Other')], max_length=100),
        ),
    ]
