# Generated by Django 5.0.4 on 2024-04-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0002_remove_equipment_cpu_remove_equipment_gpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='booking_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
