# Generated by Django 5.0.4 on 2024-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0002_remove_equipment_cpu_remove_equipment_gpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='accessLevel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
