# Generated by Django 5.0.4 on 2024-04-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0003_alter_equipment_accesslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='comments',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
