# Generated by Django 5.0.4 on 2024-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0004_alter_equipment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='auditDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipmentName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipmentStatus',
            field=models.CharField(choices=[('On_loan', 'On Loan'), ('Repairing', 'Repairing'), ('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipmentType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(choices=[('blue_cabinet', 'XRLab Blue Cabinet'), ('blue_cabinet_large', 'XRLab Blue Cabinet Large'), ('medium_wooden_cabinet', 'XRLab Medium Wooden Cabinet'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serialNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
