# Generated by Django 5.0.4 on 2024-05-01 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0003_equipment_booking_count'),
        ('equipment_management', '0006_alter_equipment_auditdate_and_more'),
    ]

    operations = [
    ]
