# Generated by Django 5.0.4 on 2024-05-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0007_merge_20240501_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='booking_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
