# Generated by Django 5.0.4 on 2024-05-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0008_alter_equipment_booking_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='booking_count',
            new_name='bookingCount',
        ),
    ]
