# Generated by Django 5.0.4 on 2024-05-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0009_rename_booking_count_equipment_bookingcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='auditDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serialNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
