# Generated by Django 5.0.4 on 2024-04-26 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='report',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='Default Report Name', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='pdf',
            field=models.FileField(default='report name', upload_to='reports/', verbose_name='PDF File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='report name', max_length=100, verbose_name='Report Type'),
            preserve_default=False,
        ),
    ]
