# Generated by Django 5.0.4 on 2024-04-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_management', '0002_remove_report_comments_remove_report_creationdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
    ]
