# Generated by Django 5.0.4 on 2024-04-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_management', '0003_remove_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Report Type'),
        ),
    ]
