# Generated by Django 5.0.4 on 2024-04-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateField()),
                ('checkoutDate', models.DateField()),
                ('expectedReturnDate', models.DateField()),
                ('approvalStatus', models.CharField(max_length=100)),
                ('isCancelled', models.BooleanField(default=False)),
                ('equipment_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
