# Generated by Django 5.0.4 on 2024-04-30 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0002_remove_equipment_cpu_remove_equipment_gpu_and_more'),
        ('user_account', '0002_reservationlist_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationlist',
            name='equipment_id',
        ),
        migrations.RemoveField(
            model_name='reservationlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='reservationlist',
            name='equipment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationlist',
            name='userID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
