# Generated by Django 5.0.4 on 2024-05-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_reservationlist_returned_alter_reservationlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlist',
            name='bookingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
